// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGbeUovCiz7fw021sVffODfSM7_WYp5XQ',
    appId: '1:835895355070:web:48e8b7cf1339988813a0ef',
    messagingSenderId: '835895355070',
    projectId: 'apphasia-7a930',
    authDomain: 'apphasia-7a930.firebaseapp.com',
    storageBucket: 'apphasia-7a930.firebasestorage.app',
    measurementId: 'G-E7G9PD2JKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6YpL_3oJ9Cep4eOibzIBs410Lc5vNZ7s',
    appId: '1:835895355070:android:b6c2e5d2a8532fcd13a0ef',
    messagingSenderId: '835895355070',
    projectId: 'apphasia-7a930',
    storageBucket: 'apphasia-7a930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bzKozmIp05ZpKRvHH-Xk24pDXTJV2C4',
    appId: '1:835895355070:ios:c0936dde8afec7bc13a0ef',
    messagingSenderId: '835895355070',
    projectId: 'apphasia-7a930',
    storageBucket: 'apphasia-7a930.firebasestorage.app',
    iosBundleId: 'com.example.aphasiaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6bzKozmIp05ZpKRvHH-Xk24pDXTJV2C4',
    appId: '1:835895355070:ios:c0936dde8afec7bc13a0ef',
    messagingSenderId: '835895355070',
    projectId: 'apphasia-7a930',
    storageBucket: 'apphasia-7a930.firebasestorage.app',
    iosBundleId: 'com.example.aphasiaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGbeUovCiz7fw021sVffODfSM7_WYp5XQ',
    appId: '1:835895355070:web:62744510cfd302d013a0ef',
    messagingSenderId: '835895355070',
    projectId: 'apphasia-7a930',
    authDomain: 'apphasia-7a930.firebaseapp.com',
    storageBucket: 'apphasia-7a930.firebasestorage.app',
    measurementId: 'G-XWK9FK5C6F',
  );
}
